### PR TITLE
Add unit tests for com.crossoverjie.actual.Search

### PR DESCRIPTION
**Pull request by JohnLBergqvist**
如果是文字类 PR，请按照 [中文排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines) 进行编写(提交时可删除该提示)。

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Unit Tests

**The description of the PR:**
I've analysed your codebase and noticed that `com.crossoverjie.actual.Search` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

**Other information:**

### CODE REVIEW

**Review by freddytuxworth — APPROVED** [review]

**Review by paulkennethkent — CHANGES_REQUESTED** [review]
Are there any other classes that could be added to this? It seems rather small. 
I have an outstanding PR with this project btw.

**Comment by JohnLBergqvist** [comment]
@paulkennethkent The Unit Generator didn't pick up anything else.

**Review by petersear — COMMENTED** [review]
There are asserts for searches in main() in the source class. Does that mean this is already (partially?) covered?

**Comment by JohnLBergqvist** [comment]
Fine, i'll give up.

**Pull request closed without merging**
